name: Publish to PyPI

on:
  pull_request:
    branches:
      - main
      
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: make restore_dev

      - name: Run flake
        run: make static_code_analysis

      - name: Run mypy
        run: make check_types

      - name: Run bandit
        run: make bandit

      - name: Run unit tests
        run: make unit_tests

      - name: Unit tests report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unittests
          path: test-results.xml
          reporter: java-junit

      - name: Build the package
        run: make build

      - name: Publish to PyPI
        if: github.ref_name == 'main'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv pip install twine
          uv run twine upload dist/*
